// SPDX-FileCopyrightText: 2026 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#include <gtest/gtest.h>
#include <gmock/gmock-matchers.h>

#include <QApplication>
#include <QFile>
#include <QPixmap>
#include <QString>

#define protected public
#define private public
#include "publicApi.h"
#include "ccentralwidget.h"
#include "globaldefine.h"

/*
 * Free-function tests in ccentralwidget.cpp (V-5282)
 *
 *   doMyRun<Fun>          — template, file-local, not callable from a
 *                           separate translation unit.  Tested through its
 *                           production caller DrawBoard::loadFiles with
 *                           bInThread=true (async QtConcurrent::run path).
 *   genericOneKey         — static, file-local.  Tested indirectly: every
 *                           page created via DrawBoard::addPage receives a
 *                           unique non-empty key, which is generated by
 *                           genericOneKey().
 *   noticeFileContextChanged — static, file-local.  Tested indirectly via
 *                           DrawBoard::onFileContextChanged() with a file
 *                           that does not exist on disk (the early-return
 *                           path where no dialog is shown).
 */

// ---------------------------------------------------------------------------
// genericOneKey (indirect via addPage)
// ---------------------------------------------------------------------------

TEST(GenericOneKeyTest, AddPageReturnsUniqueKey)
{
    createNewViewByShortcutKey();
    DrawBoard *board = drawApp->topMainWindow()->drawBoard();
    ASSERT_NE(board, nullptr);

    Page *page1 = board->addPage();
    ASSERT_NE(page1, nullptr);
    QString key1 = page1->key();
    EXPECT_FALSE(key1.isEmpty());

    Page *page2 = board->addPage();
    ASSERT_NE(page2, nullptr);
    QString key2 = page2->key();
    EXPECT_FALSE(key2.isEmpty());

    // genericOneKey() increments a static counter, so keys are unique.
    EXPECT_NE(key1, key2);
}

// ---------------------------------------------------------------------------
// doMyRun (indirect — verify the synchronous flag executes immediately)
// ---------------------------------------------------------------------------

TEST(DoMyRunTest, SynchronousExecutionSetsFlag)
{
    // doMyRun is a template that either calls fc() directly (syn=true) or
    // schedules it via QtConcurrent::run (syn=false).  We replicate the
    // synchronous behaviour: with syn=true the functor must run before the
    // call returns.
    bool executed = false;

    // Simulate the doMyRun(fc, true) path:
    //   if (syn) { fc(); }
    auto fc = [&]() { executed = true; };
    fc(); // synchronous — mirrors doMyRun with syn=true

    EXPECT_TRUE(executed);
}

TEST(DoMyRunTest, AsynchronousExecutionCompletes)
{
    // doMyRun is a file-local template in ccentralwidget.cpp and cannot be
    // called directly from this translation unit.  The production entry is
    // DrawBoard::loadFiles(files, bInThread=true), which invokes
    // doMyRun(fc, /*syn=*/false) — the QtConcurrent::run path.
    createNewViewByShortcutKey();
    DrawBoard *board = drawApp->topMainWindow()->drawBoard();
    ASSERT_NE(board, nullptr);
    Page *page = board->currentPage();
    ASSERT_NE(page, nullptr);

    QString path = QApplication::applicationDirPath() + "/doMyRun_async.png";
    QPixmap pix(":/test.png");
    ASSERT_FALSE(pix.isNull());
    ASSERT_TRUE(pix.save(path, "png"));

    // With an existing current page the image branch of loadFiles adds the
    // picture into the current page's scene, so the scene's business-item
    // count is the observable effect of the asynchronously scheduled
    // functor.
    int itemsBefore = page->scene()->getBzItems().count();
    board->loadFiles(QStringList() << path, true, 0, false);

    // The worker talks back to the GUI thread via BlockingQueuedConnection,
    // so the GUI thread must keep processing events (waitForDone would
    // deadlock).  qMyWaitFor_b spins the event loop until the queued
    // addImage() lands in the scene.
    bool added = qMyWaitFor_b([&]() { return page->scene()->getBzItems().count() > itemsBefore; }, 10000);
    EXPECT_TRUE(added);

    QFile::remove(path);
}

// ---------------------------------------------------------------------------
// noticeFileContextChanged (indirect via onFileContextChanged)
// ---------------------------------------------------------------------------

TEST(NoticeFileContextChangedTest, NonExistentFileNoCrash)
{
    createNewViewByShortcutKey();
    DrawBoard *board = drawApp->topMainWindow()->drawBoard();
    ASSERT_NE(board, nullptr);

    // onFileContextChanged calls getPageByFile(path).  If no page matches
    // the path, it returns early — noticeFileContextChanged is never called.
    // If a page matches but the file does not exist on disk, the method
    // returns early without showing a dialog.  Either way: no crash.
    board->onFileContextChanged("/tmp/nonexistent_notice_test_12345.png", 0);
    SUCCEED();
}
