/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.Picker.xml -p color_picker_interface -c ColorPickerInterface
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef COLOR_PICKER_INTERFACE_H
#define COLOR_PICKER_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.Picker
 */
class ColorPickerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.Picker"; }

public:
    ColorPickerInterface(const QString &service, const QString &path,
                         const QDBusConnection &connection, QObject *parent = 0);

    ~ColorPickerInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> StartPick(const QString &appid)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(appid);
        return asyncCallWithArgumentList(QStringLiteral("StartPick"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void colorPicked(const QString &appid, const QString &color);
};

namespace com {
  namespace deepin {
    typedef ::ColorPickerInterface Picker;
  }
}
#endif
