/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusDraw -p dbusdraw com.deepin.Draw.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusdraw.h"

/*
 * Implementation of interface class DBusDraw
 */

DBusDraw::DBusDraw(QObject *parent)
    : QDBusAbstractInterface(staticInterfaceName(),  staticInterfacePath(),
                             staticInterfaceName(), QDBusConnection::sessionBus(), parent)
{
}

DBusDraw::~DBusDraw()
{
}

