.\" This file is processed to generate manpages in the
.\" build diretory.
.TH deepin-draw 1  "2021-03-03" "Deepin"

.SH NAME
deepin\-draw \- the Drawing board from UOS

.SH SYNOPSIS
.B deepin\-draw
[\fIPATH\fR]

.SH DESCRIPTION
.B Deepin Draw 
is a lightweight drawing tool for users to freely draw and simply edit images. 

.PP
This program does not accept any command line options.

If \fIPATH\fR is specified, you can use Draw to open the .ddf file or picture.
If you omit \fIPATH\fR, you can open Draw and display all .ddf files or pictures in it.
If Draw is started, use Draw to open the .ddf file.
Otherwise, start Draw and use it to open the .ddf file.

.SH SEE ALSO
https://github.com/linuxdeepin/deepin-draw

.SH AUTHOR
.PP
.B deepin\-draw
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT wangyicun@\:uniontech.com
Wang Yicun
.ME
for the Debian Project (but may be used by others).
